# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-07 07:10


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkle', '0008_auto_20151209_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparkleversion',
            name='is_critical',
            field=models.BooleanField(default=False),
        ),
    ]
