# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-17 08:04


from django.db import migrations
import versionfield


class Migration(migrations.Migration):

    dependencies = [
        ('sparkle', '0009_sparkleversion_is_critical'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparkleversion',
            name='_short_version',
            field=versionfield.VersionField(blank=True, help_text='Format: 255.255.65535.65535', null=True),
        ),
        migrations.AddField(
            model_name='sparkleversion',
            name='_version',
            field=versionfield.VersionField(db_index=True, default=0, help_text='Format: 65535.65535'),
            preserve_default=False,
        ),
    ]
