# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-17 08:44


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparkle', '0011_auto_20170317_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparkleversion',
            name='short_version',
        ),
        migrations.RemoveField(
            model_name='sparkleversion',
            name='version',
        ),
        migrations.RenameField(
            model_name='sparkleversion',
            old_name='_short_version',
            new_name='short_version',
        ),
        migrations.RenameField(
            model_name='sparkleversion',
            old_name='_version',
            new_name='version',
        ),
    ]
