# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-05-14 07:55


from django.db import migrations
import versionfield


class Migration(migrations.Migration):

    dependencies = [
        ('sparkle', '0013_auto_20170918_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparkleversion',
            name='minimum_system_version',
            field=versionfield.VersionField(blank=True, help_text='Format: 255.255.255', null=True),
        ),
    ]
