# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-09 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparkle', '0014_sparkleversion_minimum_system_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparkleversion',
            name='dsa_signature',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='DSA signature'),
        ),
    ]
