# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-09 04:31
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_auto_20160608_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_data',
            field=jsonfield.fields.JSONField(blank=True, help_text='JSON format', null=True, verbose_name='Feedback data'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
    ]
