# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-10-23 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DecryptionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_decrypted', models.BooleanField(default=False)),
                ('encrypted_aes_key', models.TextField()),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name=b'created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name=b'modified')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name=b'created')),
                ('type', models.CharField(choices=[(b'db', b'Database'), (b'custom', b'Custom')], max_length=32)),
                ('is_enabled', models.BooleanField(default=True)),
                ('private_key', models.TextField(blank=True)),
                ('public_key', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='decryptiondata',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encryption.GeneratedKey'),
        ),
    ]
