# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-10-25 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decryptiondata',
            name='key',
        ),
        migrations.AddField(
            model_name='decryptiondata',
            name='key_id',
            field=models.TextField(),
            preserve_default=False,
        ),
    ]
