# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: annotations.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import math_pb2
import dom_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='annotations.proto',
  package='userfeedback',
  serialized_pb=_b('\n\x11\x61nnotations.proto\x12\x0cuserfeedback\x1a\nmath.proto\x1a\tdom.proto\"\x7f\n\nAnnotation\x12*\n\trectangle\x18\x01 \x02(\x0b\x32\x17.userfeedback.Rectangle\x12\x0f\n\x07snippet\x18\x02 \x01(\t\x12\x34\n\x14\x61nnotatedElementPath\x18\x03 \x01(\x0b\x32\x16.userfeedback.HtmlPathB\x02H\x03')
  ,
  dependencies=[math_pb2.DESCRIPTOR,dom_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ANNOTATION = _descriptor.Descriptor(
  name='Annotation',
  full_name='userfeedback.Annotation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rectangle', full_name='userfeedback.Annotation.rectangle', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='snippet', full_name='userfeedback.Annotation.snippet', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='annotatedElementPath', full_name='userfeedback.Annotation.annotatedElementPath', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=185,
)

_ANNOTATION.fields_by_name['rectangle'].message_type = math_pb2._RECTANGLE
_ANNOTATION.fields_by_name['annotatedElementPath'].message_type = dom_pb2._HTMLPATH
DESCRIPTOR.message_types_by_name['Annotation'] = _ANNOTATION

Annotation = _reflection.GeneratedProtocolMessageType('Annotation', (_message.Message,), dict(
  DESCRIPTOR = _ANNOTATION,
  __module__ = 'annotations_pb2'
  # @@protoc_insertion_point(class_scope:userfeedback.Annotation)
  ))
_sym_db.RegisterMessage(Annotation)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
