# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common.proto',
  package='userfeedback',
  serialized_pb=_b('\n\x0c\x63ommon.proto\x12\x0cuserfeedback\"\xcd\x01\n\nCommonData\x12\x0f\n\x07gaia_id\x18\x01 \x01(\x06\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x1e\n\x16\x64\x65scription_translated\x18\x04 \x01(\t\x12\'\n\x1bsource_description_language\x18\x05 \x01(\t:\x02\x65n\x12\x1a\n\x0bui_language\x18\x06 \x01(\t:\x05\x65n_US\x12\x12\n\nuser_email\x18\x03 \x01(\t\x12 \n\x18unique_report_identifier\x18\x07 \x01(\tB\x02H\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_COMMONDATA = _descriptor.Descriptor(
  name='CommonData',
  full_name='userfeedback.CommonData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gaia_id', full_name='userfeedback.CommonData.gaia_id', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='userfeedback.CommonData.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description_translated', full_name='userfeedback.CommonData.description_translated', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='source_description_language', full_name='userfeedback.CommonData.source_description_language', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("en").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ui_language', full_name='userfeedback.CommonData.ui_language', index=4,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("en_US").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_email', full_name='userfeedback.CommonData.user_email', index=5,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unique_report_identifier', full_name='userfeedback.CommonData.unique_report_identifier', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=236,
)

DESCRIPTOR.message_types_by_name['CommonData'] = _COMMONDATA

CommonData = _reflection.GeneratedProtocolMessageType('CommonData', (_message.Message,), dict(
  DESCRIPTOR = _COMMONDATA,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:userfeedback.CommonData)
  ))
_sym_db.RegisterMessage(CommonData)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
