# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='config.proto',
  package='userfeedback',
  serialized_pb=_b('\n\x0c\x63onfig.proto\x12\x0cuserfeedback\"2\n\x07Product\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\r\n\x05owner\x18\x03 \x03(\t\"\xa2\x06\n\x10\x46\x65\x65\x64\x62\x61\x63kTypeData\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0f\n\x07\x65nabled\x18\x02 \x02(\x08\x12\x14\n\x0cproblem_name\x18\x03 \x02(\t\x12\x14\n\x0cproduct_name\x18\x04 \x01(\t\x12*\n\x07matcher\x18\x06 \x02(\x0b\x32\x19.userfeedback.MatcherData\x12\x1a\n\x12notification_email\x18\x07 \x02(\t\x12:\n\x04kind\x18\x0b \x01(\x0e\x32#.userfeedback.FeedbackTypeData.Kind:\x07PRODUCT\x12\x16\n\x0esummary_prefix\x18\x0c \x01(\t\x12\x10\n\x08template\x18\r \x01(\t\x12\x12\n\nproduct_id\x18\x0e \x01(\x05\x12\x0b\n\x03tag\x18\x0f \x01(\t\x12\x1b\n\x13problem_description\x18\x10 \x01(\t\x12G\n\nvisibility\x18\x11 \x01(\x0e\x32).userfeedback.FeedbackTypeData.Visibility:\x08INTERNAL\x12K\n\x0enotify_channel\x18\x14 \x01(\x0e\x32,.userfeedback.FeedbackTypeData.NotifyChannel:\x05\x45MAIL\x12\x62\n\x18notification_granularity\x18\x15 \x01(\x0e\x32\x36.userfeedback.FeedbackTypeData.NotificationGranularity:\x08\x46\x45\x45\x44\x42\x41\x43K\x12\x1f\n\x14\x63lustering_threshold\x18\x16 \x01(\x05:\x01\x35\" \n\x04Kind\x12\x0b\n\x07PRODUCT\x10\x01\x12\x0b\n\x07SPECIAL\x10\x02\"(\n\nVisibility\x12\x0c\n\x08\x45XTERNAL\x10\x01\x12\x0c\n\x08INTERNAL\x10\x02\"<\n\rNotifyChannel\x12\t\n\x05\x45MAIL\x10\x01\x12\r\n\tBUGANIZER\x10\x02\x12\x11\n\rISSUE_TRACKER\x10\x03\"4\n\x17NotificationGranularity\x12\x0c\n\x08\x46\x45\x45\x44\x42\x41\x43K\x10\x01\x12\x0b\n\x07\x43LUSTER\x10\x02\"_\n\x0bMatcherData\x12\x17\n\x0f\x63ontent_matcher\x18\x01 \x02(\t\x12\x13\n\x0burl_matcher\x18\x02 \x02(\t\x12\"\n\x14url_matcher_approved\x18\x03 \x01(\x08:\x04trueB\x02H\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_FEEDBACKTYPEDATA_KIND = _descriptor.EnumDescriptor(
  name='Kind',
  full_name='userfeedback.FeedbackTypeData.Kind',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PRODUCT', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPECIAL', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=695,
  serialized_end=727,
)
_sym_db.RegisterEnumDescriptor(_FEEDBACKTYPEDATA_KIND)

_FEEDBACKTYPEDATA_VISIBILITY = _descriptor.EnumDescriptor(
  name='Visibility',
  full_name='userfeedback.FeedbackTypeData.Visibility',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EXTERNAL', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERNAL', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=729,
  serialized_end=769,
)
_sym_db.RegisterEnumDescriptor(_FEEDBACKTYPEDATA_VISIBILITY)

_FEEDBACKTYPEDATA_NOTIFYCHANNEL = _descriptor.EnumDescriptor(
  name='NotifyChannel',
  full_name='userfeedback.FeedbackTypeData.NotifyChannel',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EMAIL', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BUGANIZER', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ISSUE_TRACKER', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=771,
  serialized_end=831,
)
_sym_db.RegisterEnumDescriptor(_FEEDBACKTYPEDATA_NOTIFYCHANNEL)

_FEEDBACKTYPEDATA_NOTIFICATIONGRANULARITY = _descriptor.EnumDescriptor(
  name='NotificationGranularity',
  full_name='userfeedback.FeedbackTypeData.NotificationGranularity',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FEEDBACK', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLUSTER', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=833,
  serialized_end=885,
)
_sym_db.RegisterEnumDescriptor(_FEEDBACKTYPEDATA_NOTIFICATIONGRANULARITY)


_PRODUCT = _descriptor.Descriptor(
  name='Product',
  full_name='userfeedback.Product',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='userfeedback.Product.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='userfeedback.Product.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='owner', full_name='userfeedback.Product.owner', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=80,
)


_FEEDBACKTYPEDATA = _descriptor.Descriptor(
  name='FeedbackTypeData',
  full_name='userfeedback.FeedbackTypeData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='userfeedback.FeedbackTypeData.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='enabled', full_name='userfeedback.FeedbackTypeData.enabled', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='problem_name', full_name='userfeedback.FeedbackTypeData.problem_name', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='product_name', full_name='userfeedback.FeedbackTypeData.product_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='matcher', full_name='userfeedback.FeedbackTypeData.matcher', index=4,
      number=6, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='notification_email', full_name='userfeedback.FeedbackTypeData.notification_email', index=5,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kind', full_name='userfeedback.FeedbackTypeData.kind', index=6,
      number=11, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='summary_prefix', full_name='userfeedback.FeedbackTypeData.summary_prefix', index=7,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='template', full_name='userfeedback.FeedbackTypeData.template', index=8,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='product_id', full_name='userfeedback.FeedbackTypeData.product_id', index=9,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag', full_name='userfeedback.FeedbackTypeData.tag', index=10,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='problem_description', full_name='userfeedback.FeedbackTypeData.problem_description', index=11,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='visibility', full_name='userfeedback.FeedbackTypeData.visibility', index=12,
      number=17, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='notify_channel', full_name='userfeedback.FeedbackTypeData.notify_channel', index=13,
      number=20, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='notification_granularity', full_name='userfeedback.FeedbackTypeData.notification_granularity', index=14,
      number=21, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clustering_threshold', full_name='userfeedback.FeedbackTypeData.clustering_threshold', index=15,
      number=22, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=5,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FEEDBACKTYPEDATA_KIND,
    _FEEDBACKTYPEDATA_VISIBILITY,
    _FEEDBACKTYPEDATA_NOTIFYCHANNEL,
    _FEEDBACKTYPEDATA_NOTIFICATIONGRANULARITY,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=885,
)


_MATCHERDATA = _descriptor.Descriptor(
  name='MatcherData',
  full_name='userfeedback.MatcherData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='content_matcher', full_name='userfeedback.MatcherData.content_matcher', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='url_matcher', full_name='userfeedback.MatcherData.url_matcher', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='url_matcher_approved', full_name='userfeedback.MatcherData.url_matcher_approved', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=887,
  serialized_end=982,
)

_FEEDBACKTYPEDATA.fields_by_name['matcher'].message_type = _MATCHERDATA
_FEEDBACKTYPEDATA.fields_by_name['kind'].enum_type = _FEEDBACKTYPEDATA_KIND
_FEEDBACKTYPEDATA.fields_by_name['visibility'].enum_type = _FEEDBACKTYPEDATA_VISIBILITY
_FEEDBACKTYPEDATA.fields_by_name['notify_channel'].enum_type = _FEEDBACKTYPEDATA_NOTIFYCHANNEL
_FEEDBACKTYPEDATA.fields_by_name['notification_granularity'].enum_type = _FEEDBACKTYPEDATA_NOTIFICATIONGRANULARITY
_FEEDBACKTYPEDATA_KIND.containing_type = _FEEDBACKTYPEDATA
_FEEDBACKTYPEDATA_VISIBILITY.containing_type = _FEEDBACKTYPEDATA
_FEEDBACKTYPEDATA_NOTIFYCHANNEL.containing_type = _FEEDBACKTYPEDATA
_FEEDBACKTYPEDATA_NOTIFICATIONGRANULARITY.containing_type = _FEEDBACKTYPEDATA
DESCRIPTOR.message_types_by_name['Product'] = _PRODUCT
DESCRIPTOR.message_types_by_name['FeedbackTypeData'] = _FEEDBACKTYPEDATA
DESCRIPTOR.message_types_by_name['MatcherData'] = _MATCHERDATA

Product = _reflection.GeneratedProtocolMessageType('Product', (_message.Message,), dict(
  DESCRIPTOR = _PRODUCT,
  __module__ = 'config_pb2'
  # @@protoc_insertion_point(class_scope:userfeedback.Product)
  ))
_sym_db.RegisterMessage(Product)

FeedbackTypeData = _reflection.GeneratedProtocolMessageType('FeedbackTypeData', (_message.Message,), dict(
  DESCRIPTOR = _FEEDBACKTYPEDATA,
  __module__ = 'config_pb2'
  # @@protoc_insertion_point(class_scope:userfeedback.FeedbackTypeData)
  ))
_sym_db.RegisterMessage(FeedbackTypeData)

MatcherData = _reflection.GeneratedProtocolMessageType('MatcherData', (_message.Message,), dict(
  DESCRIPTOR = _MATCHERDATA,
  __module__ = 'config_pb2'
  # @@protoc_insertion_point(class_scope:userfeedback.MatcherData)
  ))
_sym_db.RegisterMessage(MatcherData)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
