# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dom.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dom.proto',
  package='userfeedback',
  serialized_pb=_b('\n\tdom.proto\x12\x0cuserfeedback\"_\n\x0cHtmlDocument\x12\x0b\n\x03url\x18\x01 \x02(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x33\n\x10\x64ocument_element\x18\x03 \x01(\x0b\x32\x19.userfeedback.HtmlElement\"\xad\x01\n\x0bHtmlElement\x12\x10\n\x08tag_name\x18\x01 \x02(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x12\n\nclass_name\x18\x03 \x01(\t\x12\x30\n\rchild_element\x18\x04 \x03(\x0b\x32\x19.userfeedback.HtmlElement\x12:\n\x16\x66rame_content_document\x18\x05 \x01(\x0b\x32\x1a.userfeedback.HtmlDocument\"\xbb\x02\n\tNavigator\x12\x15\n\rapp_code_name\x18\x01 \x01(\t\x12\x10\n\x08\x61pp_name\x18\x02 \x01(\t\x12\x13\n\x0b\x61pp_version\x18\x03 \x01(\t\x12\x19\n\x11\x61pp_minor_version\x18\x04 \x01(\t\x12\x16\n\x0e\x63ookie_enabled\x18\x05 \x01(\x08\x12\x11\n\tcpu_class\x18\x06 \x01(\t\x12\x0f\n\x07on_line\x18\x07 \x01(\x08\x12\x10\n\x08platform\x18\x08 \x01(\t\x12\x18\n\x10\x62rowser_language\x18\t \x01(\t\x12\x17\n\x0fsystem_language\x18\n \x01(\t\x12\x12\n\nuser_agent\x18\x0b \x01(\t\x12\x14\n\x0cjava_enabled\x18\x0c \x01(\x08\x12\x15\n\rtaint_enabled\x18\r \x01(\x08\x12\x13\n\x0bplugin_name\x18\x0e \x03(\t\"\x19\n\x08HtmlPath\x12\r\n\x05index\x18\x01 \x03(\x05\x42\x02H\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_HTMLDOCUMENT = _descriptor.Descriptor(
  name='HtmlDocument',
  full_name='userfeedback.HtmlDocument',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='userfeedback.HtmlDocument.url', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='title', full_name='userfeedback.HtmlDocument.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='document_element', full_name='userfeedback.HtmlDocument.document_element', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=122,
)


_HTMLELEMENT = _descriptor.Descriptor(
  name='HtmlElement',
  full_name='userfeedback.HtmlElement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tag_name', full_name='userfeedback.HtmlElement.tag_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='userfeedback.HtmlElement.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='class_name', full_name='userfeedback.HtmlElement.class_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='child_element', full_name='userfeedback.HtmlElement.child_element', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='frame_content_document', full_name='userfeedback.HtmlElement.frame_content_document', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=298,
)


_NAVIGATOR = _descriptor.Descriptor(
  name='Navigator',
  full_name='userfeedback.Navigator',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='app_code_name', full_name='userfeedback.Navigator.app_code_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='app_name', full_name='userfeedback.Navigator.app_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='app_version', full_name='userfeedback.Navigator.app_version', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='app_minor_version', full_name='userfeedback.Navigator.app_minor_version', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cookie_enabled', full_name='userfeedback.Navigator.cookie_enabled', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cpu_class', full_name='userfeedback.Navigator.cpu_class', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='on_line', full_name='userfeedback.Navigator.on_line', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='platform', full_name='userfeedback.Navigator.platform', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='browser_language', full_name='userfeedback.Navigator.browser_language', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='system_language', full_name='userfeedback.Navigator.system_language', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_agent', full_name='userfeedback.Navigator.user_agent', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='java_enabled', full_name='userfeedback.Navigator.java_enabled', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='taint_enabled', full_name='userfeedback.Navigator.taint_enabled', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='plugin_name', full_name='userfeedback.Navigator.plugin_name', index=13,
      number=14, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=301,
  serialized_end=616,
)


_HTMLPATH = _descriptor.Descriptor(
  name='HtmlPath',
  full_name='userfeedback.HtmlPath',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='userfeedback.HtmlPath.index', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=618,
  serialized_end=643,
)

_HTMLDOCUMENT.fields_by_name['document_element'].message_type = _HTMLELEMENT
_HTMLELEMENT.fields_by_name['child_element'].message_type = _HTMLELEMENT
_HTMLELEMENT.fields_by_name['frame_content_document'].message_type = _HTMLDOCUMENT
DESCRIPTOR.message_types_by_name['HtmlDocument'] = _HTMLDOCUMENT
DESCRIPTOR.message_types_by_name['HtmlElement'] = _HTMLELEMENT
DESCRIPTOR.message_types_by_name['Navigator'] = _NAVIGATOR
DESCRIPTOR.message_types_by_name['HtmlPath'] = _HTMLPATH

HtmlDocument = _reflection.GeneratedProtocolMessageType('HtmlDocument', (_message.Message,), dict(
  DESCRIPTOR = _HTMLDOCUMENT,
  __module__ = 'dom_pb2'
  # @@protoc_insertion_point(class_scope:userfeedback.HtmlDocument)
  ))
_sym_db.RegisterMessage(HtmlDocument)

HtmlElement = _reflection.GeneratedProtocolMessageType('HtmlElement', (_message.Message,), dict(
  DESCRIPTOR = _HTMLELEMENT,
  __module__ = 'dom_pb2'
  # @@protoc_insertion_point(class_scope:userfeedback.HtmlElement)
  ))
_sym_db.RegisterMessage(HtmlElement)

Navigator = _reflection.GeneratedProtocolMessageType('Navigator', (_message.Message,), dict(
  DESCRIPTOR = _NAVIGATOR,
  __module__ = 'dom_pb2'
  # @@protoc_insertion_point(class_scope:userfeedback.Navigator)
  ))
_sym_db.RegisterMessage(Navigator)

HtmlPath = _reflection.GeneratedProtocolMessageType('HtmlPath', (_message.Message,), dict(
  DESCRIPTOR = _HTMLPATH,
  __module__ = 'dom_pb2'
  # @@protoc_insertion_point(class_scope:userfeedback.HtmlPath)
  ))
_sym_db.RegisterMessage(HtmlPath)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
