# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: web.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import annotations_pb2
from . import dom_pb2
from . import math_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='web.proto',
  package='userfeedback',
  serialized_pb=_b('\n\tweb.proto\x12\x0cuserfeedback\x1a\x11\x61nnotations.proto\x1a\tdom.proto\x1a\nmath.proto\"\xaf\x02\n\x07WebData\x12*\n\tnavigator\x18\x01 \x01(\x0b\x32\x17.userfeedback.Navigator\x12\x39\n\x11\x65xtension_details\x18\x02 \x01(\x0b\x32\x1e.userfeedback.ExtensionDetails\x12\x0b\n\x03url\x18\x03 \x01(\t\x12,\n\nannotation\x18\x04 \x03(\x0b\x32\x18.userfeedback.Annotation\x12\x15\n\rsuggestion_id\x18\x05 \x01(\t\x12@\n\x15product_specific_data\x18\x06 \x03(\x0b\x32!.userfeedback.ProductSpecificData\x12)\n!product_specific_binary_data_name\x18\x07 \x03(\t\"G\n\x10\x45xtensionDetails\x12\x19\n\x11\x65xtension_version\x18\x01 \x02(\t\x12\x18\n\x10protocol_version\x18\x02 \x02(\t\"\\\n\x0fInternalWebData\x12\x16\n\x0e\x65mail_receiver\x18\x01 \x03(\t\x12\x0f\n\x07subject\x18\x02 \x01(\t\x12 \n\x11\x44\x45PRECATED_urgent\x18\x03 \x01(\x08:\x05\x66\x61lse\"1\n\x13ProductSpecificData\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x01(\t\"J\n\x19ProductSpecificBinaryData\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x11\n\tmime_type\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x42\x02H\x03')
  ,
  dependencies=[annotations_pb2.DESCRIPTOR,dom_pb2.DESCRIPTOR,math_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_WEBDATA = _descriptor.Descriptor(
  name='WebData',
  full_name='userfeedback.WebData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='navigator', full_name='userfeedback.WebData.navigator', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='extension_details', full_name='userfeedback.WebData.extension_details', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='url', full_name='userfeedback.WebData.url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='annotation', full_name='userfeedback.WebData.annotation', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='suggestion_id', full_name='userfeedback.WebData.suggestion_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='product_specific_data', full_name='userfeedback.WebData.product_specific_data', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='product_specific_binary_data_name', full_name='userfeedback.WebData.product_specific_binary_data_name', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=373,
)


_EXTENSIONDETAILS = _descriptor.Descriptor(
  name='ExtensionDetails',
  full_name='userfeedback.ExtensionDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='extension_version', full_name='userfeedback.ExtensionDetails.extension_version', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='protocol_version', full_name='userfeedback.ExtensionDetails.protocol_version', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=375,
  serialized_end=446,
)


_INTERNALWEBDATA = _descriptor.Descriptor(
  name='InternalWebData',
  full_name='userfeedback.InternalWebData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='email_receiver', full_name='userfeedback.InternalWebData.email_receiver', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subject', full_name='userfeedback.InternalWebData.subject', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DEPRECATED_urgent', full_name='userfeedback.InternalWebData.DEPRECATED_urgent', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=448,
  serialized_end=540,
)


_PRODUCTSPECIFICDATA = _descriptor.Descriptor(
  name='ProductSpecificData',
  full_name='userfeedback.ProductSpecificData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='userfeedback.ProductSpecificData.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='userfeedback.ProductSpecificData.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=542,
  serialized_end=591,
)


_PRODUCTSPECIFICBINARYDATA = _descriptor.Descriptor(
  name='ProductSpecificBinaryData',
  full_name='userfeedback.ProductSpecificBinaryData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='userfeedback.ProductSpecificBinaryData.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mime_type', full_name='userfeedback.ProductSpecificBinaryData.mime_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='userfeedback.ProductSpecificBinaryData.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=593,
  serialized_end=667,
)

_WEBDATA.fields_by_name['navigator'].message_type = dom_pb2._NAVIGATOR
_WEBDATA.fields_by_name['extension_details'].message_type = _EXTENSIONDETAILS
_WEBDATA.fields_by_name['annotation'].message_type = annotations_pb2._ANNOTATION
_WEBDATA.fields_by_name['product_specific_data'].message_type = _PRODUCTSPECIFICDATA
DESCRIPTOR.message_types_by_name['WebData'] = _WEBDATA
DESCRIPTOR.message_types_by_name['ExtensionDetails'] = _EXTENSIONDETAILS
DESCRIPTOR.message_types_by_name['InternalWebData'] = _INTERNALWEBDATA
DESCRIPTOR.message_types_by_name['ProductSpecificData'] = _PRODUCTSPECIFICDATA
DESCRIPTOR.message_types_by_name['ProductSpecificBinaryData'] = _PRODUCTSPECIFICBINARYDATA

WebData = _reflection.GeneratedProtocolMessageType('WebData', (_message.Message,), dict(
  DESCRIPTOR = _WEBDATA,
  __module__ = 'web_pb2'
  # @@protoc_insertion_point(class_scope:userfeedback.WebData)
  ))
_sym_db.RegisterMessage(WebData)

ExtensionDetails = _reflection.GeneratedProtocolMessageType('ExtensionDetails', (_message.Message,), dict(
  DESCRIPTOR = _EXTENSIONDETAILS,
  __module__ = 'web_pb2'
  # @@protoc_insertion_point(class_scope:userfeedback.ExtensionDetails)
  ))
_sym_db.RegisterMessage(ExtensionDetails)

InternalWebData = _reflection.GeneratedProtocolMessageType('InternalWebData', (_message.Message,), dict(
  DESCRIPTOR = _INTERNALWEBDATA,
  __module__ = 'web_pb2'
  # @@protoc_insertion_point(class_scope:userfeedback.InternalWebData)
  ))
_sym_db.RegisterMessage(InternalWebData)

ProductSpecificData = _reflection.GeneratedProtocolMessageType('ProductSpecificData', (_message.Message,), dict(
  DESCRIPTOR = _PRODUCTSPECIFICDATA,
  __module__ = 'web_pb2'
  # @@protoc_insertion_point(class_scope:userfeedback.ProductSpecificData)
  ))
_sym_db.RegisterMessage(ProductSpecificData)

ProductSpecificBinaryData = _reflection.GeneratedProtocolMessageType('ProductSpecificBinaryData', (_message.Message,), dict(
  DESCRIPTOR = _PRODUCTSPECIFICBINARYDATA,
  __module__ = 'web_pb2'
  # @@protoc_insertion_point(class_scope:userfeedback.ProductSpecificBinaryData)
  ))
_sym_db.RegisterMessage(ProductSpecificBinaryData)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
