# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-11 10:48
from __future__ import unicode_literals

import crash.models
from django.db import migrations, models
from django.db.models import Q


def delete_empty_crashes(apps, schema_editor):
    Crash = apps.get_model("crash", "Crash")
    empty_crashes = Crash.objects.filter(Q(upload_file_minidump='') | Q(upload_file_minidump__isnull=True))
    empty_crashes.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('crash', '0024_auto_20151216_1245'),
    ]

    operations = [
        migrations.RunSQL('SET CONSTRAINTS ALL IMMEDIATE',
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunPython(delete_empty_crashes, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='crash',
            name='upload_file_minidump',
            field=models.FileField(max_length=255, upload_to=crash.models.crash_upload_to),
        ),
        migrations.RunSQL('SET CONSTRAINTS ALL IMMEDIATE',
                          reverse_sql=migrations.RunSQL.noop),
    ]
