# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-04 06:01


import crash.models
import omaha_server.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crash', '0025_set_symbols_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbols',
            name='file',
            field=models.FileField(null=True, storage=omaha_server.utils.StorageWithSpaces(), upload_to=crash.models.symbols_upload_to),
        ),
    ]
