# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-03 07:27
from __future__ import unicode_literals
import os

from django.db import models, migrations


def update_symbols_urls(apps, schema_editor):
    Symbol = apps.get_model("crash", "Symbols")
    symbols = Symbol.objects.filter(debug_file__contains=' ').iterator()
    for symbol in symbols:
        head, tail = os.path.split(symbol.file.name)
        symbol.file.name = os.path.join(head, '%s.sym' % symbol.debug_file)
        symbol.save()


class Migration(migrations.Migration):

    dependencies = [
        ('crash', '0025_set_symbols_size'),
    ]

    operations = [
        migrations.RunPython(
            update_symbols_urls,
            reverse_code=migrations.RunPython.noop
        ),
    ]
