# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-14 10:56
from __future__ import unicode_literals

from django.db import migrations


def update_symbols_urls(apps, schema_editor):
    Crash = apps.get_model("crash", "Crash")
    crashes = Crash.objects.all().iterator()
    for obj in crashes:
        obj.os = obj.stacktrace_json.get('system_info', {}).get('os', '') if obj.stacktrace_json else ''
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('crash', '0028_crash_os'),
    ]

    operations = [
        migrations.RunPython(
            update_symbols_urls,
            reverse_code=migrations.RunPython.noop
        ),
    ]
