# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-17 06:47


from django.db import migrations


def update_crashes(apps, schema_editor):
    Crash = apps.get_model("crash", "Crash")
    crashes = Crash.objects.all().iterator()
    for obj in crashes:
        obj.os = obj.stacktrace_json.get('system_info', {}).get('os', '') if obj.stacktrace_json else ''
        obj.build_number = obj.meta.get('ver', '') if obj.meta else ''
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('crash', '0029_crash_build_number'),
    ]

    operations = [
        migrations.RunPython(
            update_crashes,
            reverse_code=migrations.RunPython.noop
        ),
    ]
