# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-22 09:18


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crash', '0030_auto_20170417_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='crash',
            name='channel',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
    ]
