# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-14 07:00


import crash.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crash', '0032_auto_20170710_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crash',
            name='archive',
            field=models.FileField(blank=True, max_length=255, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=crash.models.crash_archive_upload_to),
        ),
        migrations.AlterField(
            model_name='crash',
            name='upload_file_minidump',
            field=models.FileField(blank=True, max_length=255, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=crash.models.crash_upload_to),
        ),
    ]
