# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-09 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crash', '0034_auto_20170918_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crash',
            name='channel',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='crash',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
    ]
