# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-10-23 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0001_initial'),
        ('crash', '0034_auto_20170918_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='crash',
            name='decryption_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encryption.DecryptionData'),
        ),
    ]
