# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 07:20


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omaha', '0026_grant_permission_django_site'),
    ]

    operations = [
        migrations.RunSQL('DROP TABLE IF EXISTS httplog_entry;', reverse_sql=migrations.RunSQL.noop),
    ]

