# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 08:25


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omaha', '0027_auto_20160707_0720'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='os',
            unique_together=set([('platform', 'version', 'sp', 'arch')]),
        ),
    ]
