# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-09 09:14


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omaha', '0027_auto_20160713_0755'),
        ('omaha', '0028_auto_20160707_0825'),
    ]

    operations = [
    ]
