# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-28 07:46


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omaha', '0029_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='is_critical',
            field=models.BooleanField(default=False),
        ),
    ]
