# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-07 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import omaha.models
import versionfield


class Migration(migrations.Migration):

    dependencies = [
        ('omaha', '0029_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('source_version', versionfield.VersionField(blank=True, db_index=True, help_text='Format: 255.255.65535.65535', null=True)),
                ('file', models.FileField(upload_to=omaha.models._package_upload_to)),
                ('file_hash', models.CharField(blank=True, max_length=140, null=True, verbose_name='Hash')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='version',
            name='file',
        ),
        migrations.RemoveField(
            model_name='version',
            name='file_hash',
        ),
        migrations.RemoveField(
            model_name='version',
            name='file_size',
        ),
        migrations.AddField(
            model_name='package',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omaha.Version'),
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together=set([('version', 'source_version')]),
        ),
        migrations.AlterIndexTogether(
            name='package',
            index_together=set([('version', 'source_version')]),
        ),
    ]
