# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-25 09:39


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omaha', '0030_version_is_critical'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='verbose_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
