# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-18 04:18


import django.core.files.storage
from django.db import migrations, models
import omaha.models


class Migration(migrations.Migration):

    dependencies = [
        ('omaha', '0031_platform_verbose_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='file',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=omaha.models._version_upload_to),
        ),
    ]
