# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-20 09:19


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omaha', '0032_auto_20170918_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='os',
            name='version',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
