# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-09 04:31
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields
import versionfield


class Migration(migrations.Migration):

    dependencies = [
        ('omaha', '0033_auto_20171020_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='arguments',
            field=models.CharField(blank=True, help_text='Arguments to be passed to that installer binary.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='event',
            field=models.PositiveSmallIntegerField(choices=[(0, 'preinstall'), (1, 'install'), (2, 'postinstall'), (3, 'update')], help_text='Contains a fixed string denoting when this action should be run.'),
        ),
        migrations.AlterField(
            model_name='action',
            name='other',
            field=jsonfield.fields.JSONField(blank=True, help_text='JSON format', null=True, verbose_name='Other attributes'),
        ),
        migrations.AlterField(
            model_name='action',
            name='run',
            field=models.CharField(blank=True, help_text='The name of an installer binary to run.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='successsaction',
            field=models.CharField(blank=True, help_text='Contains a fixed string denoting some action to take in response to a successful install', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='successurl',
            field=models.URLField(blank=True, help_text="A URL to be opened using the system's default web browser on a successful install.", null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='terminateallbrowsers',
            field=models.BooleanField(default=False, help_text='If "true", close all browser windows before starting the installer binary.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='App'),
        ),
        migrations.AlterField(
            model_name='apprequest',
            name='nextversion',
            field=versionfield.VersionField(blank=True, default=0, help_text='Format: 255.255.65535.65535', null=True),
        ),
        migrations.AlterField(
            model_name='apprequest',
            name='version',
            field=versionfield.VersionField(blank=True, default=0, help_text='Format: 255.255.65535.65535', null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Channel'),
        ),
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.PositiveSmallIntegerField(choices=[(0, 'install'), (1, 'untrusted')]),
        ),
        migrations.AlterField(
            model_name='partialupdate',
            name='active_users',
            field=models.PositiveSmallIntegerField(choices=[(0, 'all'), (1, 'week'), (2, 'month')], default=1, help_text='Active users in the past ...'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Platform'),
        ),
        migrations.AlterField(
            model_name='request',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='request',
            name='version',
            field=versionfield.VersionField(help_text='Format: 255.255.65535.65535'),
        ),
        migrations.AlterField(
            model_name='version',
            name='file_hash',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Hash'),
        ),
        migrations.AlterField(
            model_name='version',
            name='version',
            field=versionfield.VersionField(db_index=True, help_text='Format: 255.255.65535.65535'),
        ),
    ]
